In [1]:
# Import Libs
import pandas as pd

Day 01

In [3]:
# Extract Data

# PARQUET
raw_link = 'https://github.com/FranciscoFoz/7_Days_of_Code_Alura-Python-Pandas/raw/main/Dia_1-Importando_dados/Datasets/dados_exemplares.parquet'

df_parquet = pd.read_parquet(raw_link)

In [4]:
# CSV

anos = [20101, 20111, 20121, 20131, 20141, 20151, 20161, 20171, 20181, 20191, 20201, 20102, 20112, 20122, 20132, 20142, 20152, 20162, 20172, 20182, 20192]

# Lista para armazenar todos os DataFrames lidos
dfs = []

for year in anos:
    csv_link = f'https://github.com/FranciscoFoz/7_Days_of_Code_Alura-Python-Pandas/raw/main/Dia_1-Importando_dados/Datasets/dados_emprestimos/emprestimos-{year}.csv'
    df_csv = pd.read_csv(csv_link)
    dfs.append(df_csv)

In [5]:
# Transformando e saneando a base

# Concatenando todos os DataFrames
df_csv_concat = pd.concat(dfs, ignore_index=True)

# Verificando e removendo dados duplicados
df_csv_concat.drop_duplicates(inplace=True)

print(df_csv_concat.head())

   id_emprestimo codigo_barras                 data_renovacao  \
0         709684       L095049                            NaN
1         709685       L167050                            NaN
2         709686    2006017618  2010/01/26 08:07:01.738000000
3         709687       L184117  2010/01/18 11:07:46.470000000
8         709688    2007027500  2010/01/19 15:59:26.464000000

                 data_emprestimo                 data_devolucao  \
0  2010/01/04 07:44:10.721000000  2010/01/05 16:26:12.662000000
1  2010/01/04 07:44:10.750000000  2010/01/12 07:34:13.934000000
2  2010/01/04 08:08:44.081000000  2010/02/25 07:36:25.800000000
3  2010/01/04 08:24:21.284000000  2010/02/03 08:58:45.692000000
8  2010/01/04 08:27:33.569000000  2010/02/03 13:06:30.662000000

   matricula_ou_siape    tipo_vinculo_usuario
0        2.008023e+09      ALUNO DE GRADUAÇÃO
1        2.008023e+09      ALUNO DE GRADUAÇÃO
2        2.008112e+09  ALUNO DE PÓS-GRADUAÇÃO
3        2.007211e+08      ALUNO DE GRADUAÇÃO
8        2.009046e+09      ALUNO DE GRADUAÇÃO

In [6]:
# PARQUET

# Verificando e removendo dados duplicados
df_parquet.drop_duplicates(inplace=True)

In [7]:
# Merge Parquet CSV


base_full = df_parquet.merge(df_csv_concat)
base_full

,id_exemplar,codigo_barras,colecao,biblioteca,status_material,localizacao,registro_sistema,id_emprestimo,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,27,L000133_11/05/2018 08:57:56,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,691,37,818501,NaN,2010/08/17 17:00:04.440000000,2010/08/17 17:09:15.000000000,2.010060e+09,ALUNO DE GRADUAÇÃO
1,43,L000154,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,616,59,2037061,2015/08/24 21:55:47.110000000,2015/08/03 10:39:42.972000000,2015/10/19 08:52:30.000000000,2.013034e+09,ALUNO DE GRADUAÇÃO
2,61,L000267_14/07/2017 09:31:00,Dissertações,Biblioteca Central Zila Mamede,ESPECIAL,690,90,1212301,NaN,2012/03/30 14:35:52.264000000,2012/04/02 17:06:11.000000000,2.011096e+09,ALUNO DE GRADUAÇÃO
3,100,L144235,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,650,153,775420,2010/05/31 00:35:54.869000000,2010/05/14 17:58:11.558000000,2010/06/17 19:34:11.000000000,2.004286e+08,ALUNO DE GRADUAÇÃO
4,100,L144235,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,650,153,956901,2011/04/11 17:00:16.980000000,2011/03/25 19:01:29.936000000,2011/04/26 13:22:01.000000000,2.009049e+09,ALUNO DE GRADUAÇÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072517,26306,L113134,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,978,267850,1399076,2013/01/08 13:27:45.037000000,2012/12/26 10:24:33.162000000,2013/01/23 14:53:47.000000000,2.011017e+09,ALUNO DE GRADUAÇÃO
2072518,26306,L113134,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,978,267850,1558610,2013/08/22 12:11:42.207000000,2013/08/07 12:39:16.701000000,2013/08/26 12:46:53.000000000,2.009041e+09,ALUNO DE GRADUAÇÃO
2072519,26306,L113134,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,978,267850,1777379,NaN,2014/07/18 10:49:01.626000000,2014/08/14 18:22:30.000000000,2.014116e+09,ALUNO DE PÓS-GRADUAÇÃO
2072520,26306,L113134,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,978,267850,1807999,NaN,2014/08/19 18:33:03.179000000,2014/09/03 16:02:11.000000000,2.010053e+09,ALUNO DE GRADUAÇÃO
2072521,26306,L113134,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,978,267850,1839233,2014/10/08 11:40:26.797000000,2014/09/23 15:05:59.322000000,2014/10/13 17:15:46.000000000,2.010053e+09,ALUNO DE GRADUAÇÃO